#!/bin/sh  
  
set -x  
  
ENVFILE="/tmp/ovpn-env-up"  
echo "$@"  > "$ENVFILE"  
env >> "$ENVFILE"  

# TODO determine automatically
LOCAL_IP="<local public ip address>"  
FF_DEV="freifunk"  
  
  
manage_rules() {  
        ACTION="$1"  
        # TODO static rules  
        # TODO more rules so openvpn can has its own routing table which can be flushed  
        ip rule $ACTION priority 9 from all table vpn_gw  
        ip rule $ACTION priority 10 iif "$FF_DEV" table vpn  
        ip rule $ACTION priority 10 iif "$dev" table vpn  
}  
  
manage_routes() {  
        ip route $ACTION "$trusted_ip" via "$route_net_gateway" src "$LOCAL_IP" table vpn_gw  
  
        ip route $ACTION "$route_vpn_gateway" dev "$dev" src "$ifconfig_local" table vpn  
        ip route $ACTION default via "$route_vpn_gateway" src "$ifconfig_local" table vpn  
  
}  
  
  
if [ "$script_type" = "up" ]; then  
        manage_rules del || true  
        manage_rules add  
        manage_routes add  
elif [ "$script_type" = "down" ]; then  
        manage_rules del  
        manage_routes del  
fi  
  
ip route flush cache 
