#!/bin/sh

set -x

# for debugging purposes
# prints our call and env to $ENVFILE
ENVFILE="/tmp/ovpn-env-up"
echo "$@"  > "$ENVFILE"
env >> "$ENVFILE"

LOCAL_IP="<public ip of gateway machine>"
FF_DEV="freifunk"
FF_NET="10.223.0.0/16"
FF_IP="<internal ip of gateway machine>"


manage_rules() {
        ACTION="$1"
        ip rule $ACTION priority 10 iif "$FF_DEV" table vpn
        ip rule $ACTION priority 10 iif "$dev" table vpn
        ip rule $ACTION priority 10 from "$ifconfig_local" table vpn
}

add_routes() {
        ip route flush table vpn_gw
        ip route add "$trusted_ip" via "$route_net_gateway" src "$LOCAL_IP" table vpn_gw

        ip route flush table vpn
	# bad idea to add the routes for devices not related to openvpn, should be in up-script for dev
	# otherwise, a restart of freifunk dev will result in loss of this entry
        ip route add "$FF_NET" dev "FF_DEV" src "$FF_IP" src "$FF_IP" table vpn
        ip route add "$route_vpn_gateway" dev "$dev" src "$ifconfig_local" table vpn
        ip route add default via "$route_vpn_gateway" src "$ifconfig_local" table vpn

}

flush_routes() {
        ip route flush table vpn
        ip route flush table vpn_gw
}


if [ "$script_type" = "up" ]; then
        manage_rules del || true
        manage_rules add
        add_routes
elif [ "$script_type" = "down" ]; then
        manage_rules del
        flush_routes
fi

ip route flush cache

